"""
Dictionnaire complet - Traductions dans 6 langues camerounaises
Bangante, Bassa, Bafan, Bandjoun, Ewondo, Douala
"""


traductions = {
    "a quelle heure": {
        "bangante": "ne kolo",
        "bassa": "ne kolo",
        "bafan": "ne kolo",
        "bandjoun": "ne kolo",
        "ewondo": "ne kolo",
        "douala": "nə kɔlɔ",
    },
    "acheter": {
        "bangante": "keu",
        "bassa": "keu",
        "bafan": "keu",
        "bandjoun": "keu",
        "ewondo": "keu",
        "douala": "kəw",
    },
    "aller": {
        "bangante": "yeng",
        "bassa": "yeng",
        "bafan": "yeng",
        "bandjoun": "yeng",
        "ewondo": "yeng",
        "douala": "yɛŋ",
    },
    "ami": {
        "bangante": "mi lo",
        "bassa": "mi lo",
        "bafan": "mi lo",
        "bandjoun": "mi lo",
        "ewondo": "mi lo",
        "douala": "mi lɔ",
    },
    "amour": {
        "bangante": "ndo mi",
        "bassa": "ndo mi",
        "bafan": "ndo mi",
        "bandjoun": "ndo mi",
        "ewondo": "ndo mi",
        "douala": "ndɔ mi",
    },
    "ancetre": {
        "bangante": "etondo",
        "bassa": "etondo",
        "bafan": "etondo",
        "bandjoun": "etondo",
        "ewondo": "etondo",
        "douala": "ɛtɔndɔ",
    },
    "annee": {
        "bangante": "nguie",
        "bassa": "nguie",
        "bafan": "nguie",
        "bandjoun": "nguie",
        "ewondo": "nguie",
        "douala": "ŋɡwiə",
    },
    "apprendre": {
        "bangante": "tcheu lo",
        "bassa": "tcheu lo",
        "bafan": "tcheu lo",
        "bandjoun": "tcheu lo",
        "ewondo": "tcheu lo",
        "douala": "tchwə lɔ",
    },
    "apprends avec moi": {
        "bangante": "tcheu lo ke nde",
        "bassa": "tcheu lo ke nde",
        "bafan": "tcheu lo ke nde",
        "bandjoun": "tcheu lo ke nde",
        "ewondo": "tcheu lo ke nde",
        "douala": "tchwə lɔ kə ndə",
    },
    "apres-midi": {
        "bangante": "tian pepe",
        "bassa": "nwa pepe",
        "bafan": "tian pepe",
        "bandjoun": "tian pepe",
        "ewondo": "etondo pepe",
        "douala": "mukon pɛpɛ",
    },
    "arachide": {
        "bangante": "mbako",
        "bassa": "mbako",
        "bafan": "mbako",
        "bandjoun": "mbako",
        "ewondo": "mbako",
        "douala": "mbakɔ",
    },
    "araignee": {
        "bangante": "tchouok",
        "bassa": "tchouok",
        "bafan": "tchouok",
        "bandjoun": "tchouok",
        "ewondo": "tchouok",
        "douala": "tchwɔk",
    },
    "arbre": {
        "bangante": "ngheme",
        "bassa": "ngheme",
        "bafan": "ngheme",
        "bandjoun": "ngheme",
        "ewondo": "ngheme",
        "douala": "ŋɡəmə",
    },
    "attraper": {
        "bangante": "ko",
        "bassa": "ko",
        "bafan": "ko",
        "bandjoun": "ko",
        "ewondo": "ko",
        "douala": "kɔ",
    },
    "au revoir": {
        "bangante": "o o baa",
        "bassa": "yeghe",
        "bafan": "o baa",
        "bandjoun": "o baa",
        "ewondo": "e wolo",
        "douala": "na kosi",
    },
    "au temps jadis": {
        "bangante": "tian no bi loko",
        "bassa": "nwa no bi loko",
        "bafan": "tian no bi loko",
        "bandjoun": "tian no bi loko",
        "ewondo": "etondo no bi loko",
        "douala": "mukon no bi lɔkɔ",
    },
    "aujourd'hui": {
        "bangante": "tian teu",
        "bassa": "nwa teu",
        "bafan": "tian teu",
        "bandjoun": "tian teu",
        "ewondo": "etondo teu",
        "douala": "mukon teu",
    },
    "avion": {
        "bangante": "avion",
        "bassa": "avion",
        "bafan": "avion",
        "bandjoun": "avion",
        "ewondo": "avion",
        "douala": "avjɔ̃",
    },
    "avoir": {
        "bangante": "fa",
        "bassa": "fa",
        "bafan": "fa",
        "bandjoun": "fa",
        "ewondo": "fa",
        "douala": "fa",
    },
    "bateau": {
        "bangante": "bateau",
        "bassa": "bateau",
        "bafan": "bateau",
        "bandjoun": "bateau",
        "ewondo": "bateau",
        "douala": "batɔ",
    },
    "beau": {
        "bangante": "ndo lo",
        "bassa": "ndo lo",
        "bafan": "ndo lo",
        "bandjoun": "ndo lo",
        "ewondo": "ndo lo",
        "douala": "ndɔ lɔ",
    },
    "bien dormir": {
        "bangante": "ro lo",
        "bassa": "ro lo",
        "bafan": "ro lo",
        "bandjoun": "ro lo",
        "ewondo": "ro lo",
        "douala": "rɔ lɔ",
    },
    "bienvenue": {
        "bangante": "bienvenue",
        "bassa": "mi e ka ye",
        "bafan": "bienvenue",
        "bandjoun": "bienvenue",
        "ewondo": "mbaa si muno",
        "douala": "mo ti mo",
    },
    "blanc": {
        "bangante": "pene",
        "bassa": "pene",
        "bafan": "pene",
        "bandjoun": "pene",
        "ewondo": "pene",
        "douala": "pɛnə",
    },
    "blessure": {
        "bangante": "tcho tcheu",
        "bassa": "tcho tcheu",
        "bafan": "tcho tcheu",
        "bandjoun": "tcho tcheu",
        "ewondo": "tcho tcheu",
        "douala": "tchɔ tchwə",
    },
    "bleu": {
        "bangante": "tcho",
        "bassa": "tcho",
        "bafan": "tcho",
        "bandjoun": "tcho",
        "ewondo": "tcho",
        "douala": "tchɔ",
    },
    "boeuf": {
        "bangante": "ngue",
        "bassa": "ngue",
        "bafan": "ngue",
        "bandjoun": "ngue",
        "ewondo": "ngue",
        "douala": "ŋwə",
    },
    "boire": {
        "bangante": "nwe",
        "bassa": "nwe",
        "bafan": "nwe",
        "bandjoun": "nwe",
        "ewondo": "nwe",
        "douala": "nwɛ",
    },
    "bon": {
        "bangante": "lo",
        "bassa": "lo",
        "bafan": "lo",
        "bandjoun": "lo",
        "ewondo": "lo",
        "douala": "lɔ",
    },
    "bonjour": {
        "bangante": "maa gho",
        "bassa": "mieega",
        "bafan": "ma gho",
        "bandjoun": "ma gho",
        "ewondo": "mbolo",
        "douala": "mo wu",
    },
    "bonne journee": {
        "bangante": "maa gho tian",
        "bassa": "mieega nwa",
        "bafan": "ma gho tian",
        "bandjoun": "ma gho tian",
        "ewondo": "mbolo etondo",
        "douala": "mo wu mukon",
    },
    "bonne nuit": {
        "bangante": "maa gho njo",
        "bassa": "mieega njo mwo",
        "bafan": "ma gho njo",
        "bandjoun": "ma gho njo",
        "ewondo": "mbolo e mengue",
        "douala": "mo wu lengi",
    },
    "bonsoir": {
        "bangante": "maa gho nji",
        "bassa": "mieega njo",
        "bafan": "ma gho nji",
        "bandjoun": "ma gho nji",
        "ewondo": "mbolo mokon",
        "douala": "mo wu bilengi",
    },
    "bouche": {
        "bangante": "nohom",
        "bassa": "nohom",
        "bafan": "nohom",
        "bandjoun": "nohom",
        "ewondo": "nohom",
        "douala": "nohɔm",
    },
    "bras": {
        "bangante": "biaka",
        "bassa": "biaka",
        "bafan": "biaka",
        "bandjoun": "biaka",
        "ewondo": "biaka",
        "douala": "biaka",
    },
    "c'est combien": {
        "bangante": "e neffe",
        "bassa": "e neffe",
        "bafan": "e neffe",
        "bandjoun": "e neffe",
        "ewondo": "e neffe",
        "douala": "e nɛfɛ",
    },
    "c'est l'histoire de mon pere": {
        "bangante": "bi ndie papa nde",
        "bassa": "bi ndie bissou nde",
        "bafan": "bi ndie pa nde",
        "bandjoun": "bi ndie pa nde",
        "ewondo": "bi ndie bissou nde",
        "douala": "bi ndiə papa ndə",
    },
    "cacao": {
        "bangante": "kakao",
        "bassa": "kakao",
        "bafan": "kakao",
        "bandjoun": "kakao",
        "ewondo": "kakao",
        "douala": "kakao",
    },
    "cafe": {
        "bangante": "kafe",
        "bassa": "kafe",
        "bafan": "kafe",
        "bandjoun": "kafe",
        "ewondo": "kafe",
        "douala": "kafə",
    },
    "ce qui est gras ne maigrit pas": {
        "bangante": "mbeh bi pepe tcho tue",
        "bassa": "mbeh bi pepe tcho tue",
        "bafan": "mbeh bi pepe tcho tue",
        "bandjoun": "mbeh bi pepe tcho tue",
        "ewondo": "mbeh bi pepe tcho tue",
        "douala": "mbɛh bi pɛpɛ tchɔ twə",
    },
    "ceinture": {
        "bangante": "ceinture",
        "bassa": "ceinture",
        "bafan": "ceinture",
        "bandjoun": "ceinture",
        "ewondo": "ceinture",
        "douala": "sɛ̃tərə",
    },
    "celibataire": {
        "bangante": "oke mi",
        "bassa": "oke mi",
        "bafan": "oke mi",
        "bandjoun": "oke mi",
        "ewondo": "oke mi",
        "douala": "ɔkə mi",
    },
    "celui qui a honte ne fait pas d'enfants": {
        "bangante": "lo ne tcheu tcho nokue",
        "bassa": "lo ne tcheu tcho mone",
        "bafan": "lo ne tcheu tcho noke",
        "bandjoun": "lo ne tcheu tcho nokue",
        "ewondo": "lo ne tcheu tcho mone",
        "douala": "lɔ nə tchwə tchɔ mone",
    },
    "ceremonie": {
        "bangante": "lo pepe",
        "bassa": "lo pepe",
        "bafan": "lo pepe",
        "bandjoun": "lo pepe",
        "ewondo": "lo pepe",
        "douala": "lɔ pɛpɛ",
    },
    "chaise": {
        "bangante": "chaise",
        "bassa": "chaise",
        "bafan": "chaise",
        "bandjoun": "chaise",
        "ewondo": "chaise",
        "douala": "shɛzə",
    },
    "champ": {
        "bangante": "tsang",
        "bassa": "tsang",
        "bafan": "tsang",
        "bandjoun": "tsang",
        "ewondo": "tsang",
        "douala": "tsaŋ",
    },
    "chapeau": {
        "bangante": "tsap",
        "bassa": "tsap",
        "bafan": "tsap",
        "bandjoun": "tsap",
        "ewondo": "tsap",
        "douala": "tsap",
    },
    "chasseur": {
        "bangante": "teu nken",
        "bassa": "teu nken",
        "bafan": "teu nken",
        "bandjoun": "teu nken",
        "ewondo": "teu nken",
        "douala": "təw nkɛn",
    },
    "chat": {
        "bangante": "mbeko",
        "bassa": "mbeko",
        "bafan": "mbeko",
        "bandjoun": "mbeko",
        "ewondo": "mbeko",
        "douala": "mbɛkɔ",
    },
    "chaud": {
        "bangante": "pepe",
        "bassa": "pepe",
        "bafan": "pepe",
        "bandjoun": "pepe",
        "ewondo": "pepe",
        "douala": "pɛpɛ",
    },
    "chaussure": {
        "bangante": "tchousure",
        "bassa": "tchousure",
        "bafan": "tchousure",
        "bandjoun": "tchousure",
        "ewondo": "tchousure",
        "douala": "tchusərə",
    },
    "chef": {
        "bangante": "chef",
        "bassa": "chef",
        "bafan": "chef",
        "bandjoun": "chef",
        "ewondo": "chef",
        "douala": "shɛf",
    },
    "chemise": {
        "bangante": "chemise",
        "bassa": "chemise",
        "bafan": "chemise",
        "bandjoun": "chemise",
        "ewondo": "chemise",
        "douala": "chəmisə",
    },
    "chevre": {
        "bangante": "mbume",
        "bassa": "mbume",
        "bafan": "mbume",
        "bandjoun": "mbume",
        "ewondo": "mbume",
        "douala": "mbwəmə",
    },
    "chien": {
        "bangante": "tien",
        "bassa": "tien",
        "bafan": "tien",
        "bandjoun": "tien",
        "ewondo": "tien",
        "douala": "tien",
    },
    "cinq": {
        "bangante": "tono",
        "bassa": "tono",
        "bafan": "tono",
        "bandjoun": "tono",
        "ewondo": "tono",
        "douala": "tɔnɔ",
    },
    "coeur": {
        "bangante": "pwen",
        "bassa": "pwen",
        "bafan": "pwen",
        "bandjoun": "pwen",
        "ewondo": "pwen",
        "douala": "pwɛn",
    },
    "colere": {
        "bangante": "fuk",
        "bassa": "fuk",
        "bafan": "fuk",
        "bandjoun": "fuk",
        "ewondo": "fuk",
        "douala": "fuk",
    },
    "combien d'enfants as-tu": {
        "bangante": "o fa nokue meffe",
        "bassa": "o fa mone meffe",
        "bafan": "o fa noke meffe",
        "bandjoun": "o fa nokue meffe",
        "ewondo": "o fa mone meffe",
        "douala": "o fa mone məfɛ",
    },
    "comment vas-tu": {
        "bangante": "o bi ngie",
        "bassa": "o bi ngie",
        "bafan": "o bi ngie",
        "bandjoun": "o bi ngie",
        "ewondo": "o bi ngie",
        "douala": "o bi ŋɡiə",
    },
    "comprendre": {
        "bangante": "tcheu lo",
        "bassa": "tcheu lo",
        "bafan": "tcheu lo",
        "bandjoun": "tcheu lo",
        "ewondo": "tcheu lo",
        "douala": "tchwə lɔ",
    },
    "couper": {
        "bangante": "seu",
        "bassa": "seu",
        "bafan": "seu",
        "bandjoun": "seu",
        "ewondo": "seu",
        "douala": "səw",
    },
    "courage": {
        "bangante": "vongo",
        "bassa": "vongo",
        "bafan": "vongo",
        "bandjoun": "vongo",
        "ewondo": "vongo",
        "douala": "vɔŋɡɔ",
    },
    "courir": {
        "bangante": "ken",
        "bassa": "ken",
        "bafan": "ken",
        "bandjoun": "ken",
        "ewondo": "ken",
        "douala": "kɛn",
    },
    "cousin": {
        "bangante": "nenghane bi",
        "bassa": "mbang bi",
        "bafan": "ngane bi",
        "bandjoun": "nenghane bi",
        "ewondo": "mbang bi",
        "douala": "nkwɛ bi",
    },
    "coutume": {
        "bangante": "lo ndang",
        "bassa": "lo ndang",
        "bafan": "lo ndang",
        "bandjoun": "lo ndang",
        "ewondo": "lo ndang",
        "douala": "lɔ ndaŋ",
    },
    "couturier": {
        "bangante": "teu lo tissu",
        "bassa": "teu lo tissu",
        "bafan": "teu lo tissu",
        "bandjoun": "teu lo tissu",
        "ewondo": "teu lo tissu",
        "douala": "təw lɔ tisu",
    },
    "croire": {
        "bangante": "lo mbi",
        "bassa": "lo mbi",
        "bafan": "lo mbi",
        "bandjoun": "lo mbi",
        "ewondo": "lo mbi",
        "douala": "lɔ mbi",
    },
    "cuisine": {
        "bangante": "coo ndang",
        "bassa": "coo ndang",
        "bafan": "coo ndang",
        "bandjoun": "coo ndang",
        "ewondo": "coo ndang",
        "douala": "cɔɔ ndaŋ",
    },
    "dans la foret profonde": {
        "bangante": "te ngheme loko",
        "bassa": "te ngheme loko",
        "bafan": "te ngheme loko",
        "bandjoun": "te ngheme loko",
        "ewondo": "te ngheme loko",
        "douala": "tə ŋɡəmə lɔkɔ",
    },
    "dans mon village": {
        "bangante": "te ndang nde",
        "bassa": "te ndang nde",
        "bafan": "te ndang nde",
        "bandjoun": "te ndang nde",
        "ewondo": "te ndang nde",
        "douala": "tə ndaŋ ndə",
    },
    "danse": {
        "bangante": "nshie",
        "bassa": "nshie",
        "bafan": "nshie",
        "bandjoun": "nshie",
        "ewondo": "nshie",
        "douala": "nshiə",
    },
    "demain": {
        "bangante": "namje",
        "bassa": "njo",
        "bafan": "namje",
        "bandjoun": "namje",
        "ewondo": "namje",
        "douala": "namjə",
    },
    "deux": {
        "bangante": "meffe",
        "bassa": "meffe",
        "bafan": "meffe",
        "bandjoun": "meffe",
        "ewondo": "meffe",
        "douala": "məfɛ",
    },
    "dix": {
        "bangante": "mogo",
        "bassa": "mogo",
        "bafan": "mogo",
        "bandjoun": "mogo",
        "ewondo": "mogo",
        "douala": "mɔɡɔ",
    },
    "doigt": {
        "bangante": "naka tcho",
        "bassa": "mikak tcho",
        "bafan": "naka tcho",
        "bandjoun": "naka tcho",
        "ewondo": "mikak tcho",
        "douala": "mikak tchɔ",
    },
    "dormir": {
        "bangante": "ro",
        "bassa": "ro",
        "bafan": "ro",
        "bandjoun": "ro",
        "ewondo": "ro",
        "douala": "rɔ",
    },
    "dors mon enfant": {
        "bangante": "ro nokue nde",
        "bassa": "ro mone nde",
        "bafan": "ro noke nde",
        "bandjoun": "ro nokue nde",
        "ewondo": "ro mone nde",
        "douala": "rɔ mone ndə",
    },
    "dos": {
        "bangante": "nghie",
        "bassa": "nghie",
        "bafan": "nghie",
        "bandjoun": "nghie",
        "ewondo": "nghie",
        "douala": "ŋɡiə",
    },
    "doucement doucement": {
        "bangante": "ne ke ne ke",
        "bassa": "ne ke ne ke",
        "bafan": "ne ke ne ke",
        "bandjoun": "ne ke ne ke",
        "ewondo": "ne ke ne ke",
        "douala": "nə kə nə kə",
    },
    "douleur": {
        "bangante": "fuk",
        "bassa": "fuk",
        "bafan": "fuk",
        "bandjoun": "fuk",
        "ewondo": "fuk",
        "douala": "fuk",
    },
    "eau": {
        "bangante": "ngie",
        "bassa": "ngie",
        "bafan": "ngie",
        "bandjoun": "ngie",
        "ewondo": "ngie",
        "douala": "ŋɡiə",
    },
    "ecole": {
        "bangante": "ekol",
        "bassa": "ekol",
        "bafan": "ekol",
        "bandjoun": "ekol",
        "ewondo": "ekol",
        "douala": "ɛkɔl",
    },
    "ecouter": {
        "bangante": "tcheu",
        "bassa": "tcheu",
        "bafan": "tcheu",
        "bandjoun": "tcheu",
        "ewondo": "tcheu",
        "douala": "tchwə",
    },
    "ecoutez l'histoire": {
        "bangante": "tcheu lo ndie",
        "bassa": "tcheu lo ndie",
        "bafan": "tcheu lo ndie",
        "bandjoun": "tcheu lo ndie",
        "ewondo": "tcheu lo ndie",
        "douala": "tchwə lɔ ndiə",
    },
    "eglise": {
        "bangante": "lukule",
        "bassa": "lukule",
        "bafan": "lukule",
        "bandjoun": "lukule",
        "ewondo": "lukule",
        "douala": "lukulə",
    },
    "elephant": {
        "bangante": "meung",
        "bassa": "meung",
        "bafan": "meung",
        "bandjoun": "meung",
        "ewondo": "meung",
        "douala": "məwŋ",
    },
    "elle": {
        "bangante": "e mi",
        "bassa": "e mi",
        "bafan": "e mi",
        "bandjoun": "e mi",
        "ewondo": "e mi",
        "douala": "e no",
    },
    "elles": {
        "bangante": "bo mi",
        "bassa": "bo mi",
        "bafan": "bo mi",
        "bandjoun": "bo mi",
        "ewondo": "bo mi",
        "douala": "bo no",
    },
    "enfant": {
        "bangante": "nokue",
        "bassa": "mone",
        "bafan": "noke",
        "bandjoun": "nokue",
        "ewondo": "mone",
        "douala": "mone",
    },
    "ennemi": {
        "bangante": "mi tcheu",
        "bassa": "mi tcheu",
        "bafan": "mi tcheu",
        "bandjoun": "mi tcheu",
        "ewondo": "mi tcheu",
        "douala": "mi tchwə",
    },
    "enseignant": {
        "bangante": "teuchua",
        "bassa": "teuchua",
        "bafan": "teuchua",
        "bandjoun": "teuchua",
        "ewondo": "teuchua",
        "douala": "təwshua",
    },
    "enseigner": {
        "bangante": "teuchua",
        "bassa": "teuchua",
        "bafan": "teuchua",
        "bandjoun": "teuchua",
        "ewondo": "teuchua",
        "douala": "təwshua",
    },
    "epaule": {
        "bangante": "biaka",
        "bassa": "biaka",
        "bafan": "biaka",
        "bandjoun": "biaka",
        "ewondo": "biaka",
        "douala": "biaka",
    },
    "es-tu marie": {
        "bangante": "o kwe teu",
        "bassa": "o kwe teu",
        "bafan": "o kwe teu",
        "bandjoun": "o kwe teu",
        "ewondo": "o kwe teu",
        "douala": "o kwə təw",
    },
    "espoir": {
        "bangante": "mbi lo",
        "bassa": "mbi lo",
        "bafan": "mbi lo",
        "bandjoun": "mbi lo",
        "ewondo": "mbi lo",
        "douala": "mbi lɔ",
    },
    "etoile": {
        "bangante": "nshie",
        "bassa": "nshie",
        "bafan": "nshie",
        "bandjoun": "nshie",
        "ewondo": "nshie",
        "douala": "nshiə",
    },
    "etre": {
        "bangante": "bi",
        "bassa": "bi",
        "bafan": "bi",
        "bandjoun": "bi",
        "ewondo": "bi",
        "douala": "bi",
    },
    "excusez-moi": {
        "bangante": "ndaa ma",
        "bassa": "ka mi ngone",
        "bafan": "ndaa ma",
        "bandjoun": "ndaa ma",
        "ewondo": "nem ngone",
        "douala": "ka mbe si",
    },
    "faible": {
        "bangante": "tcho mbue",
        "bassa": "tcho mbue",
        "bafan": "tcho mbue",
        "bandjoun": "tcho mbue",
        "ewondo": "tcho mbue",
        "douala": "tchɔ mbwə",
    },
    "faire": {
        "bangante": "lo",
        "bassa": "lo",
        "bafan": "lo",
        "bandjoun": "lo",
        "ewondo": "lo",
        "douala": "lo",
    },
    "fatigue": {
        "bangante": "tue kaka",
        "bassa": "tue kaka",
        "bafan": "tue kaka",
        "bandjoun": "tue kaka",
        "ewondo": "tue kaka",
        "douala": "twə kaka",
    },
    "fenetre": {
        "bangante": "isho ndang",
        "bassa": "lisho ndang",
        "bafan": "isho ndang",
        "bandjoun": "isho ndang",
        "ewondo": "lisho ndang",
        "douala": "lishu ndaŋ",
    },
    "fermier": {
        "bangante": "tsang",
        "bassa": "tsang",
        "bafan": "tsang",
        "bandjoun": "tsang",
        "ewondo": "tsang",
        "douala": "tsaŋ",
    },
    "fete": {
        "bangante": "ndo lo",
        "bassa": "ndo lo",
        "bafan": "ndo lo",
        "bandjoun": "ndo lo",
        "ewondo": "ndo lo",
        "douala": "ndɔ lɔ",
    },
    "fievre": {
        "bangante": "pepe tcho",
        "bassa": "pepe tcho",
        "bafan": "pepe tcho",
        "bandjoun": "pepe tcho",
        "ewondo": "pepe tcho",
        "douala": "pɛpɛ tchɔ",
    },
    "fille": {
        "bangante": "nokue mi",
        "bassa": "mone mi",
        "bafan": "noke mi",
        "bandjoun": "nokue mi",
        "ewondo": "mone mi",
        "douala": "mone no",
    },
    "fils": {
        "bangante": "nokue roman",
        "bassa": "mone roman",
        "bafan": "noke roman",
        "bandjoun": "nokue roman",
        "ewondo": "mone met",
        "douala": "mone bik",
    },
    "fleur": {
        "bangante": "teugheme",
        "bassa": "teugheme",
        "bafan": "teugheme",
        "bandjoun": "teugheme",
        "ewondo": "teugheme",
        "douala": "təwɡəmə",
    },
    "fort": {
        "bangante": "mbue",
        "bassa": "mbue",
        "bafan": "mbue",
        "bandjoun": "mbue",
        "ewondo": "mbue",
        "douala": "mbwə",
    },
    "frere": {
        "bangante": "nenghane",
        "bassa": "mbang",
        "bafan": "ngane",
        "bandjoun": "nenghane",
        "ewondo": "mbang",
        "douala": "nkwɛ",
    },
    "froid": {
        "bangante": "tue",
        "bassa": "tue",
        "bafan": "tue",
        "bandjoun": "tue",
        "ewondo": "tue",
        "douala": "twə",
    },
    "gare": {
        "bangante": "gare",
        "bassa": "gare",
        "bafan": "gare",
        "bandjoun": "gare",
        "ewondo": "gare",
        "douala": "ɡarə",
    },
    "genou": {
        "bangante": "lote",
        "bassa": "lote",
        "bafan": "lote",
        "bandjoun": "lote",
        "ewondo": "lote",
        "douala": "lɔtə",
    },
    "gorge": {
        "bangante": "nohom nghie",
        "bassa": "nohom nghie",
        "bafan": "nohom nghie",
        "bandjoun": "nohom nghie",
        "ewondo": "nohom nghie",
        "douala": "nohɔm ŋɡiə",
    },
    "grand": {
        "bangante": "loko",
        "bassa": "loko",
        "bafan": "loko",
        "bandjoun": "loko",
        "ewondo": "loko",
        "douala": "lɔkɔ",
    },
    "grand-mere": {
        "bangante": "mama bi",
        "bassa": "mam bi",
        "bafan": "ma bi",
        "bandjoun": "mama bi",
        "ewondo": "mam etondo",
        "douala": "mama mo",
    },
    "grand-pere": {
        "bangante": "baba bi",
        "bassa": "bissou bi",
        "bafan": "pa bi",
        "bandjoun": "baba bi",
        "ewondo": "bissou etondo",
        "douala": "papa mo",
    },
    "grenier": {
        "bangante": "teu mayi",
        "bassa": "teu mayi",
        "bafan": "teu mayi",
        "bandjoun": "teu mayi",
        "ewondo": "teu mayi",
        "douala": "təw mayi",
    },
    "guerison": {
        "bangante": "lo tcho",
        "bassa": "lo tcho",
        "bafan": "lo tcho",
        "bandjoun": "lo tcho",
        "ewondo": "lo tcho",
        "douala": "lɔ tchɔ",
    },
    "hier": {
        "bangante": "tian no",
        "bassa": "nwa no",
        "bafan": "tian no",
        "bandjoun": "tian no",
        "ewondo": "etondo no",
        "douala": "mukon no",
    },
    "hopital": {
        "bangante": "hopital",
        "bassa": "hopital",
        "bafan": "hopital",
        "bandjoun": "hopital",
        "ewondo": "hopital",
        "douala": "ɔpital",
    },
    "houe": {
        "bangante": "tsongo",
        "bassa": "tsongo",
        "bafan": "tsongo",
        "bandjoun": "tsongo",
        "ewondo": "tsongo",
        "douala": "tsɔŋɡɔ",
    },
    "huile": {
        "bangante": "mbeh",
        "bassa": "mbeh",
        "bafan": "mbeh",
        "bandjoun": "mbeh",
        "ewondo": "mbeh",
        "douala": "mbɛh",
    },
    "huile de palme": {
        "bangante": "mbeh",
        "bassa": "mbeh",
        "bafan": "mbeh",
        "bandjoun": "mbeh",
        "ewondo": "mbeh",
        "douala": "mbɛh",
    },
    "huit": {
        "bangante": "loboi",
        "bassa": "loboi",
        "bafan": "loboi",
        "bandjoun": "loboi",
        "ewondo": "loboi",
        "douala": "lɔboi",
    },
    "igname": {
        "bangante": "yam",
        "bassa": "yam",
        "bafan": "yam",
        "bandjoun": "yam",
        "ewondo": "yam",
        "douala": "jam",
    },
    "il": {
        "bangante": "e",
        "bassa": "e",
        "bafan": "e",
        "bandjoun": "e",
        "ewondo": "e",
        "douala": "e",
    },
    "il etait une fois": {
        "bangante": "lo bi tcho",
        "bassa": "lo bi tcho",
        "bafan": "lo bi tcho",
        "bandjoun": "lo bi tcho",
        "ewondo": "lo bi tcho",
        "douala": "lɔ bi tchɔ",
    },
    "il fait chaud": {
        "bangante": "yo bi pepe",
        "bassa": "yo bi pepe",
        "bafan": "yo bi pepe",
        "bandjoun": "yo bi pepe",
        "ewondo": "yo bi pepe",
        "douala": "yɔ bi pɛpɛ",
    },
    "il fait froid": {
        "bangante": "yo bi tue",
        "bassa": "yo bi tue",
        "bafan": "yo bi tue",
        "bandjoun": "yo bi tue",
        "ewondo": "yo bi tue",
        "douala": "yɔ bi twə",
    },
    "il pleut": {
        "bangante": "luho bi",
        "bassa": "luho bi",
        "bafan": "luho bi",
        "bandjoun": "luho bi",
        "ewondo": "luho bi",
        "douala": "luhɔ bi",
    },
    "ils": {
        "bangante": "bo",
        "bassa": "bo",
        "bafan": "bo",
        "bandjoun": "bo",
        "ewondo": "bo",
        "douala": "bo",
    },
    "initiation": {
        "bangante": "tcheu lo",
        "bassa": "tcheu lo",
        "bafan": "tcheu lo",
        "bandjoun": "tcheu lo",
        "ewondo": "tcheu lo",
        "douala": "tchwə lɔ",
    },
    "j'ai faim": {
        "bangante": "zicounenyiom",
        "bassa": "nde coo",
        "bafan": "nde coo",
        "bandjoun": "nde coo",
        "ewondo": "nde coo",
        "douala": "nde cɔɔ",
    },
    "j'ai froid": {
        "bangante": "nde tue",
        "bassa": "nde tue",
        "bafan": "nde tue",
        "bandjoun": "nde tue",
        "ewondo": "nde tue",
        "douala": "nde twə",
    },
    "j'ai peur": {
        "bangante": "nde vio",
        "bassa": "nde vio",
        "bafan": "nde vio",
        "bandjoun": "nde vio",
        "ewondo": "nde vio",
        "douala": "nde viɔ",
    },
    "j'ai soif": {
        "bangante": "nde nwe",
        "bassa": "nde nwe",
        "bafan": "nde nwe",
        "bandjoun": "nde nwe",
        "ewondo": "nde nwe",
        "douala": "nde nwɛ",
    },
    "jaune": {
        "bangante": "pepe",
        "bassa": "pepe",
        "bafan": "pepe",
        "bandjoun": "pepe",
        "ewondo": "pepe",
        "douala": "pɛpɛ",
    },
    "je": {
        "bangante": "nde",
        "bassa": "nde",
        "bafan": "nde",
        "bandjoun": "nde",
        "ewondo": "nde",
        "douala": "nde",
    },
    "je ne comprends pas": {
        "bangante": "nde tcheu lo",
        "bassa": "nde tcheu lo",
        "bafan": "nde tcheu lo",
        "bandjoun": "nde tcheu lo",
        "ewondo": "nde tcheu lo",
        "douala": "nde tchwə lɔ",
    },
    "je parle bangante": {
        "bangante": "nde lo Bangante",
        "bassa": "nde lo Bangante",
        "bafan": "nde lo Bangante",
        "bandjoun": "nde lo Bangante",
        "ewondo": "nde lo Bangante",
        "douala": "nde lɔ Baŋɡantə",
    },
    "je parle bassa": {
        "bangante": "nde lo Bassa",
        "bassa": "nde lo Bassa",
        "bafan": "nde lo Bassa",
        "bandjoun": "nde lo Bassa",
        "ewondo": "nde lo Bassa",
        "douala": "nde lɔ Basa",
    },
    "je suis camerounais": {
        "bangante": "nde bi Cameroon",
        "bassa": "nde bi Cameroon",
        "bafan": "nde bi Cameroon",
        "bandjoun": "nde bi Cameroon",
        "ewondo": "nde bi Cameroon",
        "douala": "nde bi Kamərun",
    },
    "je suis fatigue": {
        "bangante": "nde tue kaka",
        "bassa": "nde tue kaka",
        "bafan": "nde tue kaka",
        "bandjoun": "nde tue kaka",
        "ewondo": "nde tue kaka",
        "douala": "nde twə kaka",
    },
    "je t'aime": {
        "bangante": "nde ndo mi lo",
        "bassa": "nde ndo mi lo",
        "bafan": "nde ndo mi lo",
        "bandjoun": "nde ndo mi lo",
        "ewondo": "nde ndo mi lo",
        "douala": "nde ndɔ mi lɔ",
    },
    "je vais bien": {
        "bangante": "nde bi ngie",
        "bassa": "nde bi ngie",
        "bafan": "nde bi ngie",
        "bandjoun": "nde bi ngie",
        "ewondo": "nde bi ngie",
        "douala": "nde bi ŋɡiə",
    },
    "jeter": {
        "bangante": "puo",
        "bassa": "puo",
        "bafan": "puo",
        "bandjoun": "puo",
        "ewondo": "puo",
        "douala": "puɔ",
    },
    "jeune": {
        "bangante": "tcho",
        "bassa": "tcho",
        "bafan": "tcho",
        "bandjoun": "tcho",
        "ewondo": "tcho",
        "douala": "tchɔ",
    },
    "joie": {
        "bangante": "ndo",
        "bassa": "ndo",
        "bafan": "ndo",
        "bandjoun": "ndo",
        "ewondo": "ndo",
        "douala": "ndɔ",
    },
    "jupe": {
        "bangante": "jupe",
        "bassa": "jupe",
        "bafan": "jupe",
        "bandjoun": "jupe",
        "ewondo": "jupe",
        "douala": "jupə",
    },
    "l'homme propose dieu dispose": {
        "bangante": "lo lo bi o lo",
        "bassa": "lo lo bi o lo",
        "bafan": "lo lo bi o lo",
        "bandjoun": "lo lo bi o lo",
        "ewondo": "lo lo bi o lo",
        "douala": "lɔ lɔ bi o lɔ",
    },
    "la main qui donne est au-dessus": {
        "bangante": "naka ne pua bi pepe",
        "bassa": "mikak ne pua bi pepe",
        "bafan": "naka ne pua bi pepe",
        "bandjoun": "naka ne pua bi pepe",
        "ewondo": "mikak ne pua bi pepe",
        "douala": "mikak nə puɔ bi pɛpɛ",
    },
    "la nuit est calme": {
        "bangante": "njo bi mbi",
        "bassa": "njo bi mbi",
        "bafan": "njo bi mbi",
        "bandjoun": "njo bi mbi",
        "ewondo": "mengue bi mbi",
        "douala": "lengi bi mbi",
    },
    "la paresse ne recolte pas": {
        "bangante": "tcho tcheu tcho bi mayi",
        "bassa": "tcho tcheu tcho bi mayi",
        "bafan": "tcho tcheu tcho bi mayi",
        "bandjoun": "tcho tcheu tcho bi mayi",
        "ewondo": "tcho tcheu tcho bi mayi",
        "douala": "tchɔ tchwə tchɔ bi mayi",
    },
    "la verite marche meme pieds nus": {
        "bangante": "ndo bi dang tcho tchep",
        "bassa": "ndo bi dang tcho tchep",
        "bafan": "ndo bi dang tcho tchep",
        "bandjoun": "ndo bi dang tcho tchep",
        "ewondo": "ndo bi dang tcho tchep",
        "douala": "ndɔ bi daŋ tchɔ tchɛp",
    },
    "laid": {
        "bangante": "ndo teu",
        "bassa": "ndo teu",
        "bafan": "ndo teu",
        "bandjoun": "ndo teu",
        "ewondo": "ndo teu",
        "douala": "ndɔ təw",
    },
    "le ciel est beau": {
        "bangante": "shie bi ndo lo",
        "bassa": "shie bi ndo lo",
        "bafan": "shie bi ndo lo",
        "bandjoun": "shie bi ndo lo",
        "ewondo": "shie bi ndo lo",
        "douala": "shiə bi ndɔ lɔ",
    },
    "le lion et le lievre": {
        "bangante": "kene lo nshie",
        "bassa": "kene lo nshie",
        "bafan": "kene lo nshie",
        "bandjoun": "kene lo nshie",
        "ewondo": "kene lo nshie",
        "douala": "kɛnə lɔ nshiə",
    },
    "le silence est d'or": {
        "bangante": "tcheu lo pepe",
        "bassa": "tcheu lo pepe",
        "bafan": "tcheu lo pepe",
        "bandjoun": "tcheu lo pepe",
        "ewondo": "tcheu lo pepe",
        "douala": "tchwə lɔ pɛpɛ",
    },
    "le village brule et la mere pue le poisson": {
        "bangante": "ndang fuk mama tcheu bem",
        "bassa": "ndang fuk mama tcheu bem",
        "bafan": "ndang fuk mama tcheu bem",
        "bandjoun": "ndang fuk mama tcheu bem",
        "ewondo": "ndang fuk mama tcheu bem",
        "douala": "ndaŋ fuk mama tchwə bɛm",
    },
    "legume": {
        "bangante": "ndole",
        "bassa": "ndole",
        "bafan": "ndole",
        "bandjoun": "ndole",
        "ewondo": "ndole",
        "douala": "ndɔlə",
    },
    "les anciens disaient": {
        "bangante": "bo etondo lo",
        "bassa": "bo etondo lo",
        "bafan": "bo etondo lo",
        "bandjoun": "bo etondo lo",
        "ewondo": "bo etondo lo",
        "douala": "bo ɛtɔndɔ lɔ",
    },
    "les etoiles brillent": {
        "bangante": "nshie bi pepe",
        "bassa": "nshie bi pepe",
        "bafan": "nshie bi pepe",
        "bandjoun": "nshie bi pepe",
        "ewondo": "nshie bi pepe",
        "douala": "nshiə bi pɛpɛ",
    },
    "lion": {
        "bangante": "kene",
        "bassa": "kene",
        "bafan": "kene",
        "bandjoun": "kene",
        "ewondo": "kene",
        "douala": "kɛnə",
    },
    "lit": {
        "bangante": "ndam",
        "bassa": "ndam",
        "bafan": "ndam",
        "bandjoun": "ndam",
        "ewondo": "ndam",
        "douala": "ndam",
    },
    "lune": {
        "bangante": "ngie",
        "bassa": "ngie",
        "bafan": "ngie",
        "bandjoun": "ngie",
        "ewondo": "ngie",
        "douala": "ŋɡiə",
    },
    "ma grand-mere racontait": {
        "bangante": "mama bi lo",
        "bassa": "mam bi lo",
        "bafan": "ma bi lo",
        "bandjoun": "mama bi lo",
        "ewondo": "mam etondo lo",
        "douala": "mama mo lɔ",
    },
    "magasin": {
        "bangante": "magasin",
        "bassa": "magasin",
        "bafan": "magasin",
        "bandjoun": "magasin",
        "ewondo": "magasin",
        "douala": "maɡasin",
    },
    "main": {
        "bangante": "naka",
        "bassa": "mikak",
        "bafan": "naka",
        "bandjoun": "naka",
        "ewondo": "mikak",
        "douala": "mikak",
    },
    "mais": {
        "bangante": "kpo",
        "bassa": "kpo",
        "bafan": "kpo",
        "bandjoun": "kpo",
        "ewondo": "kpo",
        "douala": "kpo",
    },
    "maison": {
        "bangante": "ndang",
        "bassa": "ndang",
        "bafan": "ndang",
        "bandjoun": "ndang",
        "ewondo": "ndang",
        "douala": "ndaŋ",
    },
    "maladie": {
        "bangante": "tcho kaka",
        "bassa": "tcho kaka",
        "bafan": "tcho kaka",
        "bandjoun": "tcho kaka",
        "ewondo": "tcho kaka",
        "douala": "tchɔ kaka",
    },
    "maman est la": {
        "bangante": "mama bi teu",
        "bassa": "mam bi teu",
        "bafan": "ma bi teu",
        "bandjoun": "mama bi teu",
        "ewondo": "mam bi teu",
        "douala": "mama bi təw",
    },
    "manger": {
        "bangante": "coo",
        "bassa": "coo",
        "bafan": "coo",
        "bandjoun": "coo",
        "ewondo": "coo",
        "douala": "cɔɔ",
    },
    "marchand": {
        "bangante": "teu djang",
        "bassa": "teu djang",
        "bafan": "teu djang",
        "bandjoun": "teu djang",
        "ewondo": "teu djang",
        "douala": "təw djaŋ",
    },
    "marche": {
        "bangante": "djang",
        "bassa": "djang",
        "bafan": "djang",
        "bandjoun": "djang",
        "ewondo": "djang",
        "douala": "djaŋ",
    },
    "marcher": {
        "bangante": "dang",
        "bassa": "dang",
        "bafan": "dang",
        "bandjoun": "dang",
        "ewondo": "dang",
        "douala": "daŋ",
    },
    "mari": {
        "bangante": "kwe",
        "bassa": "kwe",
        "bafan": "kwe",
        "bandjoun": "kwe",
        "ewondo": "kwe",
        "douala": "kwə",
    },
    "masque": {
        "bangante": "loko ndo",
        "bassa": "lihi ndo",
        "bafan": "loko ndo",
        "bandjoun": "loko ndo",
        "ewondo": "lihi ndo",
        "douala": "lihi ndɔ",
    },
    "matin": {
        "bangante": "shie",
        "bassa": "shie",
        "bafan": "shie",
        "bandjoun": "shie",
        "ewondo": "shie",
        "douala": "shiə",
    },
    "mauvais": {
        "bangante": "teu",
        "bassa": "teu",
        "bafan": "teu",
        "bandjoun": "teu",
        "ewondo": "teu",
        "douala": "təw",
    },
    "medecin": {
        "bangante": "ngang",
        "bassa": "ngang",
        "bafan": "ngang",
        "bandjoun": "ngang",
        "ewondo": "ngang",
        "douala": "ŋɡaŋ",
    },
    "medicament": {
        "bangante": "ngang",
        "bassa": "ngang",
        "bafan": "ngang",
        "bandjoun": "ngang",
        "ewondo": "ngang",
        "douala": "ŋɡaŋ",
    },
    "menuisier": {
        "bangante": "teu lo ndang",
        "bassa": "teu lo ndang",
        "bafan": "teu lo ndang",
        "bandjoun": "teu lo ndang",
        "ewondo": "teu lo ndang",
        "douala": "təw lɔ ndaŋ",
    },
    "merci": {
        "bangante": "melapte",
        "bassa": "me laka",
        "bafan": "me lape",
        "bandjoun": "melapte",
        "ewondo": "esiame",
        "douala": "si bo",
    },
    "mere": {
        "bangante": "mama",
        "bassa": "mam",
        "bafan": "ma",
        "bandjoun": "ma",
        "ewondo": "mam",
        "douala": "mama",
    },
    "mois": {
        "bangante": "moon",
        "bassa": "moon",
        "bafan": "moon",
        "bandjoun": "moon",
        "ewondo": "moon",
        "douala": "mon",
    },
    "montagne": {
        "bangante": "loko ndie",
        "bassa": "lihi ndie",
        "bafan": "loko ndie",
        "bandjoun": "loko ndie",
        "ewondo": "lihi ndie",
        "douala": "lihi ndiə",
    },
    "mort": {
        "bangante": "fue",
        "bassa": "fue",
        "bafan": "fue",
        "bandjoun": "fue",
        "ewondo": "fue",
        "douala": "fwə",
    },
    "moto": {
        "bangante": "moto",
        "bassa": "moto",
        "bafan": "moto",
        "bandjoun": "moto",
        "ewondo": "moto",
        "douala": "mɔtɔ",
    },
    "mouche": {
        "bangante": "mbui",
        "bassa": "mbui",
        "bafan": "mbui",
        "bandjoun": "mbui",
        "ewondo": "mbui",
        "douala": "mbui",
    },
    "mur": {
        "bangante": "tcheu ndang",
        "bassa": "tcheu ndang",
        "bafan": "tcheu ndang",
        "bandjoun": "tcheu ndang",
        "ewondo": "tcheu ndang",
        "douala": "tchwə ndaŋ",
    },
    "neuf": {
        "bangante": "bongo",
        "bassa": "bongo",
        "bafan": "bongo",
        "bandjoun": "bongo",
        "ewondo": "bongo",
        "douala": "bɔŋɡɔ",
    },
    "nez": {
        "bangante": "nhem",
        "bassa": "nhem",
        "bafan": "nhem",
        "bandjoun": "nhem",
        "ewondo": "nhem",
        "douala": "nhɛm",
    },
    "noir": {
        "bangante": "tchue",
        "bassa": "tchue",
        "bafan": "tchue",
        "bandjoun": "tchue",
        "ewondo": "tchue",
        "douala": "tchwe",
    },
    "nous": {
        "bangante": "ndi",
        "bassa": "ndi",
        "bafan": "ndi",
        "bandjoun": "ndi",
        "ewondo": "ndi",
        "douala": "ndi",
    },
    "nuit": {
        "bangante": "njo",
        "bassa": "njo",
        "bafan": "njo",
        "bandjoun": "njo",
        "ewondo": "mengue",
        "douala": "lengi",
    },
    "oeil": {
        "bangante": "isho",
        "bassa": "lisho",
        "bafan": "isho",
        "bandjoun": "isho",
        "ewondo": "lisho",
        "douala": "lishu",
    },
    "oignon": {
        "bangante": "tchiamb",
        "bassa": "tchiamb",
        "bafan": "tchiamb",
        "bandjoun": "tchiamb",
        "ewondo": "tchiamb",
        "douala": "tchiamb",
    },
    "oiseau": {
        "bangante": "nem",
        "bassa": "nem",
        "bafan": "nem",
        "bandjoun": "nem",
        "ewondo": "nem",
        "douala": "nɛm",
    },
    "oncle": {
        "bangante": "kaka",
        "bassa": "kaka",
        "bafan": "ka",
        "bandjoun": "kaka",
        "ewondo": "kaka",
        "douala": "kaka",
    },
    "orange": {
        "bangante": "pepe peli",
        "bassa": "pepe peli",
        "bafan": "pepe peli",
        "bandjoun": "pepe peli",
        "ewondo": "pepe peli",
        "douala": "pɛpɛ pɛli",
    },
    "oreille": {
        "bangante": "tchoke",
        "bassa": "tchok",
        "bafan": "tchoke",
        "bandjoun": "tchoke",
        "ewondo": "tchok",
        "douala": "tchɔk",
    },
    "ou est": {
        "bangante": "e teu",
        "bassa": "e teu",
        "bafan": "e teu",
        "bandjoun": "e teu",
        "ewondo": "e teu",
        "douala": "e təw",
    },
    "ou travailles-tu": {
        "bangante": "o lo teu",
        "bassa": "o lo teu",
        "bafan": "o lo teu",
        "bandjoun": "o lo teu",
        "ewondo": "o lo teu",
        "douala": "o lɔ təw",
    },
    "pain": {
        "bangante": "pain",
        "bassa": "pain",
        "bafan": "pain",
        "bandjoun": "pain",
        "ewondo": "pain",
        "douala": "pɛn",
    },
    "paix": {
        "bangante": "mbi",
        "bassa": "mbi",
        "bafan": "mbi",
        "bandjoun": "mbi",
        "ewondo": "mbi",
        "douala": "mbi",
    },
    "pantalon": {
        "bangante": "pantalоn",
        "bassa": "pantalon",
        "bafan": "pantalon",
        "bandjoun": "pantalon",
        "ewondo": "pantalon",
        "douala": "patalɔn",
    },
    "parler": {
        "bangante": "lo",
        "bassa": "lo",
        "bafan": "lo",
        "bandjoun": "lo",
        "ewondo": "lo",
        "douala": "lɔ",
    },
    "parlez plus lentement": {
        "bangante": "lo ne ke",
        "bassa": "lo ne ke",
        "bafan": "lo ne ke",
        "bandjoun": "lo ne ke",
        "ewondo": "lo ne ke",
        "douala": "lɔ nə kə",
    },
    "parole est un oeuf": {
        "bangante": "lo bi oke",
        "bassa": "lo bi oke",
        "bafan": "lo bi oke",
        "bandjoun": "lo bi oke",
        "ewondo": "lo bi oke",
        "douala": "lɔ bi ɔkə",
    },
    "pasteur": {
        "bangante": "pasteur",
        "bassa": "pasteur",
        "bafan": "pasteur",
        "bandjoun": "pasteur",
        "ewondo": "pasteur",
        "douala": "pastɛr",
    },
    "patate": {
        "bangante": "mbape",
        "bassa": "mbape",
        "bafan": "mbape",
        "bandjoun": "mbape",
        "ewondo": "mbape",
        "douala": "mbapə",
    },
    "patience est mere de vertu": {
        "bangante": "tue bi mama lo",
        "bassa": "tue bi mama lo",
        "bafan": "tue bi mama lo",
        "bandjoun": "tue bi mama lo",
        "ewondo": "tue bi mama lo",
        "douala": "twə bi mama lɔ",
    },
    "pauvre": {
        "bangante": "lo teu",
        "bassa": "lo teu",
        "bafan": "lo teu",
        "bandjoun": "lo teu",
        "ewondo": "lo teu",
        "douala": "lɔ təw",
    },
    "pecheur": {
        "bangante": "teu bem",
        "bassa": "teu bem",
        "bafan": "teu bem",
        "bandjoun": "teu bem",
        "ewondo": "teu bem",
        "douala": "təw bɛm",
    },
    "pere": {
        "bangante": "papa",
        "bassa": "bissou",
        "bafan": "pa",
        "bandjoun": "pa",
        "ewondo": "bissou",
        "douala": "papa",
    },
    "petit": {
        "bangante": "tcho",
        "bassa": "tcho",
        "bafan": "tcho",
        "bandjoun": "tcho",
        "ewondo": "tcho",
        "douala": "tchɔ",
    },
    "peur": {
        "bangante": "vio",
        "bassa": "vio",
        "bafan": "vio",
        "bandjoun": "vio",
        "ewondo": "vio",
        "douala": "viɔ",
    },
    "pied": {
        "bangante": "tchep",
        "bassa": "tchep",
        "bafan": "tchep",
        "bandjoun": "tchep",
        "ewondo": "tchep",
        "douala": "tchɛp",
    },
    "piment": {
        "bangante": "hotia",
        "bassa": "hotia",
        "bafan": "hotia",
        "bandjoun": "hotia",
        "ewondo": "hotia",
        "douala": "hɔtia",
    },
    "pluie": {
        "bangante": "luho",
        "bassa": "luho",
        "bafan": "luho",
        "bandjoun": "luho",
        "ewondo": "luho",
        "douala": "luhɔ",
    },
    "plusieurs mains levent le poids": {
        "bangante": "mikak meffe tue mbua",
        "bassa": "mikak meffe tue mbua",
        "bafan": "mikak meffe tue mbua",
        "bandjoun": "mikak meffe tue mbua",
        "ewondo": "mikak meffe tue mbua",
        "douala": "mikak məfɛ təw mbua",
    },
    "poisson": {
        "bangante": "bem",
        "bassa": "bem",
        "bafan": "bem",
        "bandjoun": "bem",
        "ewondo": "bem",
        "douala": "bɛm",
    },
    "pont": {
        "bangante": "lote",
        "bassa": "lote",
        "bafan": "lote",
        "bandjoun": "lote",
        "ewondo": "lote",
        "douala": "lɔtə",
    },
    "porte": {
        "bangante": "loko ndang",
        "bassa": "lihi ndang",
        "bafan": "loko ndang",
        "bandjoun": "loko ndang",
        "ewondo": "lihi ndang",
        "douala": "lihi ndaŋ",
    },
    "porter": {
        "bangante": "teu",
        "bassa": "teu",
        "bafan": "teu",
        "bandjoun": "teu",
        "ewondo": "teu",
        "douala": "təw",
    },
    "poulet": {
        "bangante": "nsua",
        "bassa": "nsua",
        "bafan": "nsua",
        "bandjoun": "nsua",
        "ewondo": "nsua",
        "douala": "nsua",
    },
    "prier": {
        "bangante": "nguie",
        "bassa": "nguie",
        "bafan": "nguie",
        "bandjoun": "nguie",
        "ewondo": "nguie",
        "douala": "ŋɡwiə",
    },
    "prix": {
        "bangante": "neffe",
        "bassa": "neffe",
        "bafan": "neffe",
        "bandjoun": "neffe",
        "ewondo": "neffe",
        "douala": "nɛfɛ",
    },
    "profit": {
        "bangante": "mbua",
        "bassa": "mbua",
        "bafan": "mbua",
        "bandjoun": "mbua",
        "ewondo": "mbua",
        "douala": "mbua",
    },
    "quand j'etais petit": {
        "bangante": "ke nde bi tcho",
        "bassa": "ke nde bi tcho",
        "bafan": "ke nde bi tcho",
        "bandjoun": "ke nde bi tcho",
        "ewondo": "ke nde bi tcho",
        "douala": "kə ndə bi tchɔ",
    },
    "quand le singe tombe on lui coupe la queue": {
        "bangante": "bok tue bo seu naka",
        "bassa": "bok tue bo seu naka",
        "bafan": "bok tue bo seu naka",
        "bandjoun": "bok tue bo seu naka",
        "ewondo": "bok tue bo seu naka",
        "douala": "bɔk twə bo səw naka",
    },
    "quand on veut on peut": {
        "bangante": "ke o vio o lo",
        "bassa": "ke o vio o lo",
        "bafan": "ke o vio o lo",
        "bandjoun": "ke o vio o lo",
        "ewondo": "ke o vio o lo",
        "douala": "kə o viɔ o lɔ",
    },
    "quatre": {
        "bangante": "nai",
        "bassa": "nai",
        "bafan": "nai",
        "bandjoun": "nai",
        "ewondo": "nai",
        "douala": "nai",
    },
    "que fais-tu dans la vie": {
        "bangante": "o lo teu",
        "bassa": "o lo teu",
        "bafan": "o lo teu",
        "bandjoun": "o lo teu",
        "ewondo": "o lo teu",
        "douala": "o lɔ təw",
    },
    "quel age as-tu": {
        "bangante": "o fa moon meffe",
        "bassa": "o fa moon meffe",
        "bafan": "o fa moon meffe",
        "bandjoun": "o fa moon meffe",
        "ewondo": "o fa moon meffe",
        "douala": "o fa mon məfɛ",
    },
    "recolte": {
        "bangante": "mayi pepe",
        "bassa": "mayi pepe",
        "bafan": "mayi pepe",
        "bandjoun": "mayi pepe",
        "ewondo": "mayi pepe",
        "douala": "mayi pɛpɛ",
    },
    "riche": {
        "bangante": "mbua",
        "bassa": "mbua",
        "bafan": "mbua",
        "bandjoun": "mbua",
        "ewondo": "mbua",
        "douala": "mbua",
    },
    "riviere": {
        "bangante": "nsie",
        "bassa": "nsie",
        "bafan": "nsie",
        "bandjoun": "nsie",
        "ewondo": "nsie",
        "douala": "nsiə",
    },
    "riz": {
        "bangante": "mayi",
        "bassa": "mayi",
        "bafan": "mayi",
        "bandjoun": "mayi",
        "ewondo": "mayi",
        "douala": "mayi",
    },
    "robe": {
        "bangante": "robe",
        "bassa": "robe",
        "bafan": "robe",
        "bandjoun": "robe",
        "ewondo": "robe",
        "douala": "rɔbə",
    },
    "rouge": {
        "bangante": "peli",
        "bassa": "peli",
        "bafan": "peli",
        "bandjoun": "peli",
        "ewondo": "peli",
        "douala": "pɛli",
    },
    "route": {
        "bangante": "tsin",
        "bassa": "tsin",
        "bafan": "tsin",
        "bandjoun": "tsin",
        "ewondo": "tsin",
        "douala": "tsin",
    },
    "s'il te plait": {
        "bangante": "ne tjouu",
        "bassa": "na mi",
        "bafan": "ne tchou",
        "bandjoun": "ne tjouu",
        "ewondo": "mbaa ke",
        "douala": "na mbe",
    },
    "sac": {
        "bangante": "sak",
        "bassa": "sak",
        "bafan": "sak",
        "bandjoun": "sak",
        "ewondo": "sak",
        "douala": "sak",
    },
    "sacrifice": {
        "bangante": "pua lo",
        "bassa": "pua lo",
        "bafan": "pua lo",
        "bandjoun": "pua lo",
        "ewondo": "pua lo",
        "douala": "puɔ lɔ",
    },
    "salut": {
        "bangante": "salut",
        "bassa": "salu",
        "bafan": "salut",
        "bandjoun": "salut",
        "ewondo": "mbolo",
        "douala": "mo wu",
    },
    "sandale": {
        "bangante": "sandale",
        "bassa": "sandale",
        "bafan": "sandale",
        "bandjoun": "sandale",
        "ewondo": "sandale",
        "douala": "sandale",
    },
    "sang": {
        "bangante": "mie",
        "bassa": "mie",
        "bafan": "mie",
        "bandjoun": "mie",
        "ewondo": "mie",
        "douala": "miə",
    },
    "sante": {
        "bangante": "bi ngie",
        "bassa": "bi ngie",
        "bafan": "bi ngie",
        "bandjoun": "bi ngie",
        "ewondo": "bi ngie",
        "douala": "bi ŋɡiə",
    },
    "sel": {
        "bangante": "ongho",
        "bassa": "ongho",
        "bafan": "ongho",
        "bandjoun": "ongho",
        "ewondo": "ongho",
        "douala": "ɔŋɡɔ",
    },
    "semaine": {
        "bangante": "semaine",
        "bassa": "semaine",
        "bafan": "semaine",
        "bandjoun": "semaine",
        "ewondo": "semaine",
        "douala": "səmɛnə",
    },
    "semence": {
        "bangante": "mayi tcho",
        "bassa": "mayi tcho",
        "bafan": "mayi tcho",
        "bandjoun": "mayi tcho",
        "ewondo": "mayi tcho",
        "douala": "mayi tchɔ",
    },
    "sept": {
        "bangante": "samba",
        "bassa": "samba",
        "bafan": "samba",
        "bandjoun": "samba",
        "ewondo": "samba",
        "douala": "samba",
    },
    "serpent": {
        "bangante": "nken",
        "bassa": "nken",
        "bafan": "nken",
        "bandjoun": "nken",
        "ewondo": "nken",
        "douala": "nkɛn",
    },
    "singe": {
        "bangante": "bok",
        "bassa": "bok",
        "bafan": "bok",
        "bandjoun": "bok",
        "ewondo": "bok",
        "douala": "bɔk",
    },
    "six": {
        "bangante": "motass",
        "bassa": "motass",
        "bafan": "motass",
        "bandjoun": "motass",
        "ewondo": "motass",
        "douala": "mɔtas",
    },
    "soeur": {
        "bangante": "nenghananmi",
        "bassa": "mi mono",
        "bafan": "ngane mi",
        "bandjoun": "nenghananmi",
        "ewondo": "mi mono",
        "douala": "nkwɛ no",
    },
    "soir": {
        "bangante": "nji",
        "bassa": "njo",
        "bafan": "nji",
        "bandjoun": "nji",
        "ewondo": "mokon",
        "douala": "bilengi",
    },
    "sol": {
        "bangante": "tsi",
        "bassa": "tsi",
        "bafan": "tsi",
        "bandjoun": "tsi",
        "ewondo": "tsi",
        "douala": "tsi",
    },
    "soleil": {
        "bangante": "yo",
        "bassa": "yo",
        "bafan": "yo",
        "bandjoun": "yo",
        "ewondo": "yo",
        "douala": "yɔ",
    },
    "sucre": {
        "bangante": "sukre",
        "bassa": "sukre",
        "bafan": "sukre",
        "bandjoun": "sukre",
        "ewondo": "sukre",
        "douala": "sukrə",
    },
    "surprise": {
        "bangante": "ndo lo",
        "bassa": "ndo lo",
        "bafan": "ndo lo",
        "bandjoun": "ndo lo",
        "ewondo": "ndo lo",
        "douala": "ndɔ lɔ",
    },
    "table": {
        "bangante": "tabee",
        "bassa": "tabee",
        "bafan": "tabee",
        "bandjoun": "tabee",
        "ewondo": "tabee",
        "douala": "tabe",
    },
    "tam-tam": {
        "bangante": "ngheu",
        "bassa": "ngheu",
        "bafan": "ngheu",
        "bandjoun": "ngheu",
        "ewondo": "ngheu",
        "douala": "ŋɡəw",
    },
    "tante": {
        "bangante": "daa",
        "bassa": "daa",
        "bafan": "da",
        "bandjoun": "daa",
        "ewondo": "daa",
        "douala": "daa",
    },
    "terre": {
        "bangante": "tsi",
        "bassa": "tsi",
        "bafan": "tsi",
        "bandjoun": "tsi",
        "ewondo": "tsi",
        "douala": "tsi",
    },
    "tete": {
        "bangante": "loko",
        "bassa": "lihi",
        "bafan": "loko",
        "bandjoun": "loko",
        "ewondo": "lihi",
        "douala": "lihi",
    },
    "the": {
        "bangante": "te",
        "bassa": "te",
        "bafan": "te",
        "bandjoun": "te",
        "ewondo": "te",
        "douala": "tə",
    },
    "tissu": {
        "bangante": "tissu",
        "bassa": "tissu",
        "bafan": "tissu",
        "bandjoun": "tissu",
        "ewondo": "tissu",
        "douala": "tisu",
    },
    "toit": {
        "bangante": "temb",
        "bassa": "temb",
        "bafan": "temb",
        "bandjoun": "temb",
        "ewondo": "temb",
        "douala": "tɛmb",
    },
    "tomate": {
        "bangante": "tomate",
        "bassa": "tomate",
        "bafan": "tomate",
        "bandjoun": "tomate",
        "ewondo": "tomate",
        "douala": "tɔmatə",
    },
    "toucher": {
        "bangante": "ka",
        "bassa": "ka",
        "bafan": "ka",
        "bandjoun": "ka",
        "ewondo": "ka",
        "douala": "ka",
    },
    "toux": {
        "bangante": "kak",
        "bassa": "kak",
        "bafan": "kak",
        "bandjoun": "kak",
        "ewondo": "kak",
        "douala": "kak",
    },
    "tradition": {
        "bangante": "lo tcho",
        "bassa": "lo tcho",
        "bafan": "lo tcho",
        "bandjoun": "lo tcho",
        "ewondo": "lo tcho",
        "douala": "lɔ tchɔ",
    },
    "tristesse": {
        "bangante": "ngiene",
        "bassa": "ngiene",
        "bafan": "ngiene",
        "bandjoun": "ngiene",
        "ewondo": "ngiene",
        "douala": "ŋɡiənə",
    },
    "trois": {
        "bangante": "lator",
        "bassa": "lator",
        "bafan": "lator",
        "bandjoun": "lator",
        "ewondo": "lator",
        "douala": "latɔr",
    },
    "tu": {
        "bangante": "o",
        "bassa": "o",
        "bafan": "o",
        "bandjoun": "o",
        "ewondo": "o",
        "douala": "o",
    },
    "tu es beau": {
        "bangante": "o bi ndo lo",
        "bassa": "o bi ndo lo",
        "bafan": "o bi ndo lo",
        "bandjoun": "o bi ndo lo",
        "ewondo": "o bi ndo lo",
        "douala": "o bi ndɔ lɔ",
    },
    "tu viens d'ou": {
        "bangante": "o ke teu",
        "bassa": "o ke teu",
        "bafan": "o ke teu",
        "bandjoun": "o ke teu",
        "ewondo": "o ke teu",
        "douala": "o kə təw",
    },
    "un": {
        "bangante": "oke",
        "bassa": "oke",
        "bafan": "oke",
        "bandjoun": "oke",
        "ewondo": "oke",
        "douala": "ɔkə",
    },
    "un grand arbre a de grandes racines": {
        "bangante": "ngheme loko bi ngheme loko",
        "bassa": "ngheme loko bi ngheme loko",
        "bafan": "ngheme loko bi ngheme loko",
        "bandjoun": "ngheme loko bi ngheme loko",
        "ewondo": "ngheme loko bi ngheme loko",
        "douala": "ŋɡəmə lɔkɔ bi ŋɡəmə lɔkɔ",
    },
    "un seul doigt ne ramasse pas le riz": {
        "bangante": "oke naka tcho tcheu mayi",
        "bassa": "oke mikak tcho tcheu mayi",
        "bafan": "oke naka tcho tcheu mayi",
        "bandjoun": "oke naka tcho tcheu mayi",
        "ewondo": "oke mikak tcho tcheu mayi",
        "douala": "ɔkə mikak tchɔ tchwə mayi",
    },
    "vache": {
        "bangante": "ngue",
        "bassa": "ngue",
        "bafan": "ngue",
        "bandjoun": "ngue",
        "ewondo": "ngue",
        "douala": "ŋwə",
    },
    "velo": {
        "bangante": "velo",
        "bassa": "velo",
        "bafan": "velo",
        "bandjoun": "velo",
        "ewondo": "velo",
        "douala": "vəlɔ",
    },
    "vent": {
        "bangante": "mbue",
        "bassa": "mbue",
        "bafan": "mbue",
        "bandjoun": "mbue",
        "ewondo": "mbue",
        "douala": "mbwə",
    },
    "ventre": {
        "bangante": "teu",
        "bassa": "teu",
        "bafan": "teu",
        "bandjoun": "teu",
        "ewondo": "teu",
        "douala": "tɛw",
    },
    "vert": {
        "bangante": "kue",
        "bassa": "kue",
        "bafan": "kue",
        "bandjoun": "kue",
        "ewondo": "kue",
        "douala": "kwə",
    },
    "viande": {
        "bangante": "nlem",
        "bassa": "nlem",
        "bafan": "nlem",
        "bandjoun": "nlem",
        "ewondo": "nlem",
        "douala": "nlɛm",
    },
    "viens ici": {
        "bangante": "ke teu nde",
        "bassa": "ke teu nde",
        "bafan": "ke teu nde",
        "bandjoun": "ke teu nde",
        "ewondo": "ke teu nde",
        "douala": "kə təw ndə",
    },
    "vieux": {
        "bangante": "etondo",
        "bassa": "etondo",
        "bafan": "etondo",
        "bandjoun": "etondo",
        "ewondo": "etondo",
        "douala": "ɛtɔndɔ",
    },
    "violet": {
        "bangante": "tcho tchue",
        "bassa": "tcho tchue",
        "bafan": "tcho tchue",
        "bandjoun": "tcho tchue",
        "ewondo": "tcho tchue",
        "douala": "tchɔ tchwe",
    },
    "voir": {
        "bangante": "lho",
        "bassa": "lho",
        "bafan": "lho",
        "bandjoun": "lho",
        "ewondo": "lho",
        "douala": "lhɔ",
    },
    "voisin": {
        "bangante": "mi tsi",
        "bassa": "mi tsi",
        "bafan": "mi tsi",
        "bandjoun": "mi tsi",
        "ewondo": "mi tsi",
        "douala": "mi tsi",
    },
    "voiture": {
        "bangante": "kamio",
        "bassa": "kamio",
        "bafan": "kamio",
        "bandjoun": "kamio",
        "ewondo": "kamio",
        "douala": "kamio",
    },
    "vous": {
        "bangante": "mi",
        "bassa": "mi",
        "bafan": "mi",
        "bandjoun": "mi",
        "ewondo": "mi",
        "douala": "mi",
    },
}


structure = {
    "debutant": {
        "Salutations": ['bonjour', 'bonsoir', 'au revoir', 'merci', "s'il te plait", 'excusez-moi', 'bienvenue', 'bonne nuit', 'bonne journee', 'salut'],
        "Famille": ['pere', 'mere', 'frere', 'soeur', 'enfant', 'fils', 'fille', 'grand-pere', 'grand-mere', 'oncle', 'tante', 'cousin'],
        "Corps humain": ['tete', 'oeil', 'oreille', 'nez', 'bouche', 'main', 'pied', 'bras', 'coeur', 'ventre'],
        "Nourriture": ['eau', 'riz', 'igname', 'mais', 'sel', 'huile', 'pain', 'poisson', 'viande', 'legume'],
        "Nombres": ['un', 'deux', 'trois', 'quatre', 'cinq', 'six', 'sept', 'huit', 'neuf', 'dix'],
        "Couleurs": ['blanc', 'noir', 'rouge', 'bleu', 'vert', 'jaune', 'orange', 'violet'],
        "Pronoms": ['je', 'tu', 'il', 'elle', 'nous', 'vous', 'ils', 'elles'],
        "Verbes basiques": ['etre', 'avoir', 'faire', 'aller', 'manger', 'dormir', 'boire'],
    },
    "moyen": {
        "Animaux": ['chien', 'chat', 'oiseau', 'vache', 'chevre', 'poulet', 'serpent', 'singe', 'elephant', 'lion', 'araignee', 'mouche'],
        "Vetements": ['chemise', 'pantalon', 'robe', 'chaussure', 'chapeau', 'jupe', 'tissu', 'sandale', 'sac', 'ceinture'],
        "Maison": ['maison', 'porte', 'fenetre', 'lit', 'table', 'chaise', 'cuisine', 'toit', 'mur', 'sol'],
        "Nature": ['soleil', 'lune', 'etoile', 'arbre', 'fleur', 'riviere', 'montagne', 'pluie', 'vent', 'terre'],
        "Ville": ['route', 'marche', 'ecole', 'hopital', 'eglise', 'magasin', 'pont', 'gare'],
        "Vehicules": ['voiture', 'moto', 'velo', 'bateau', 'avion'],
        "Professions": ['fermier', 'enseignant', 'medecin', 'menuisier', 'chasseur', 'pecheur', 'couturier', 'mari', 'pasteur', 'chef'],
        "Actions": ['marcher', 'courir', 'parler', 'ecouter', 'voir', 'toucher', 'porter', 'couper', 'jeter', 'attraper'],
    },
    "fort": {
        "Expressions courantes": ["j'ai faim", "j'ai soif", "j'ai froid", "j'ai peur", 'je suis fatigue', 'comment vas-tu', 'je vais bien', 'il fait chaud', 'il fait froid', 'il pleut', 'je ne comprends pas', 'parlez plus lentement', 'ou est', 'a quelle heure', "c'est combien"],
        "Temps": ["aujourd'hui", 'hier', 'demain', 'matin', 'apres-midi', 'soir', 'nuit', 'semaine', 'mois', 'annee'],
        "Emotions": ['joie', 'tristesse', 'colere', 'peur', 'amour', 'surprise', 'courage', 'paix', 'fatigue', 'espoir'],
        "Liens sociaux": ['ami', 'ennemi', 'voisin', 'mari', 'celibataire', 'riche', 'pauvre'],
        "Qualites": ['grand', 'petit', 'beau', 'laid', 'bon', 'mauvais', 'fort', 'faible', 'vieux', 'jeune', 'chaud', 'froid'],
        "Nourriture avancee": ['arachide', 'patate', 'tomate', 'oignon', 'piment', 'sucre', 'cafe', 'the', 'cacao', 'huile de palme'],
        "Corps avance": ['doigt', 'genou', 'epaule', 'dos', 'gorge'],
        "Verbes intermediaires": ['croire', 'comprendre', 'apprendre', 'enseigner', 'prier'],
    },
    "tres_fort": {
        "Proverbes": ['parole est un oeuf', 'quand on veut on peut', "l'homme propose dieu dispose", "le silence est d'or", 'patience est mere de vertu', 'un seul doigt ne ramasse pas le riz', 'la main qui donne est au-dessus', 'plusieurs mains levent le poids', 'la paresse ne recolte pas', 'ce qui est gras ne maigrit pas', 'le village brule et la mere pue le poisson', 'quand le singe tombe on lui coupe la queue', 'un grand arbre a de grandes racines', 'la verite marche meme pieds nus', "celui qui a honte ne fait pas d'enfants"],
        "Contes et expressions": ['il etait une fois', 'au temps jadis', 'dans mon village', 'les anciens disaient', "quand j'etais petit", 'ma grand-mere racontait', "ecoutez l'histoire", "c'est l'histoire de mon pere", 'dans la foret profonde', 'le lion et le lievre'],
        "Chants et berceuses": ['dors mon enfant', 'viens ici', "je t'aime", 'tu es beau', 'bien dormir', 'maman est la', 'le ciel est beau', 'les etoiles brillent', 'doucement doucement', 'la nuit est calme'],
        "Conversations": ["tu viens d'ou", 'que fais-tu dans la vie', "combien d'enfants as-tu", 'ou travailles-tu', 'es-tu marie', 'quel age as-tu', 'je suis camerounais', 'je parle bangante', 'je parle bassa', 'apprends avec moi'],
        "Histoire et culture": ['ancetre', 'tradition', 'coutume', 'ceremonie', 'masque', 'danse', 'tam-tam', 'initiation', 'sacrifice', 'fete'],
        "Sante": ['maladie', 'medicament', 'douleur', 'fievre', 'toux', 'blessure', 'sang', 'guerison', 'mort', 'sante'],
        "Agriculture": ['semence', 'recolte', 'champ', 'houe', 'boeuf', 'grenier', 'prix', 'profit', 'marchand', 'acheter'],
    },
}


# Backward compatibility with old quiz system
langues = {}

bangante = {
    "debutant": {
        "bonjour": ["maa gho", "???_wrong1", "???_wrong2"],
        "bonsoir": ["maa gho nji", "???_wrong1", "???_wrong2"],
        "au revoir": ["o o baa", "???_wrong1", "???_wrong2"],
        "pere": ["papa", "???_wrong1", "???_wrong2"],
        "mere": ["mama", "???_wrong1", "???_wrong2"],
        "frere": ["nenghane", "???_wrong1", "???_wrong2"],
        "tete": ["loko", "???_wrong1", "???_wrong2"],
        "oeil": ["isho", "???_wrong1", "???_wrong2"],
        "oreille": ["tchoke", "???_wrong1", "???_wrong2"],
        "eau": ["ngie", "???_wrong1", "???_wrong2"],
        "riz": ["mayi", "???_wrong1", "???_wrong2"],
        "igname": ["yam", "???_wrong1", "???_wrong2"],
        "un": ["oke", "???_wrong1", "???_wrong2"],
        "deux": ["meffe", "???_wrong1", "???_wrong2"],
        "trois": ["lator", "???_wrong1", "???_wrong2"],
        "blanc": ["pene", "???_wrong1", "???_wrong2"],
        "noir": ["tchue", "???_wrong1", "???_wrong2"],
        "rouge": ["peli", "???_wrong1", "???_wrong2"],
        "je": ["nde", "???_wrong1", "???_wrong2"],
        "tu": ["o", "???_wrong1", "???_wrong2"],
        "il": ["e", "???_wrong1", "???_wrong2"],
        "etre": ["bi", "???_wrong1", "???_wrong2"],
        "avoir": ["fa", "???_wrong1", "???_wrong2"],
        "faire": ["lo", "???_wrong1", "???_wrong2"],
    },
    "moyen": {
        "chien": ["tien", "???_wrong1", "???_wrong2"],
        "chat": ["mbeko", "???_wrong1", "???_wrong2"],
        "oiseau": ["nem", "???_wrong1", "???_wrong2"],
        "chemise": ["chemise", "???_wrong1", "???_wrong2"],
        "pantalon": ["pantalоn", "???_wrong1", "???_wrong2"],
        "robe": ["robe", "???_wrong1", "???_wrong2"],
        "maison": ["ndang", "???_wrong1", "???_wrong2"],
        "porte": ["loko ndang", "???_wrong1", "???_wrong2"],
        "fenetre": ["isho ndang", "???_wrong1", "???_wrong2"],
        "soleil": ["yo", "???_wrong1", "???_wrong2"],
        "lune": ["ngie", "???_wrong1", "???_wrong2"],
        "etoile": ["nshie", "???_wrong1", "???_wrong2"],
        "route": ["tsin", "???_wrong1", "???_wrong2"],
        "marche": ["djang", "???_wrong1", "???_wrong2"],
        "ecole": ["ekol", "???_wrong1", "???_wrong2"],
        "voiture": ["kamio", "???_wrong1", "???_wrong2"],
        "moto": ["moto", "???_wrong1", "???_wrong2"],
        "velo": ["velo", "???_wrong1", "???_wrong2"],
        "fermier": ["tsang", "???_wrong1", "???_wrong2"],
        "enseignant": ["teuchua", "???_wrong1", "???_wrong2"],
        "medecin": ["ngang", "???_wrong1", "???_wrong2"],
        "marcher": ["dang", "???_wrong1", "???_wrong2"],
        "courir": ["ken", "???_wrong1", "???_wrong2"],
        "parler": ["lo", "???_wrong1", "???_wrong2"],
    },
    "fort": {
        "j'ai faim": ["zicounenyiom", "???_wrong1", "???_wrong2"],
        "j'ai soif": ["nde nwe", "???_wrong1", "???_wrong2"],
        "j'ai froid": ["nde tue", "???_wrong1", "???_wrong2"],
        "aujourd'hui": ["tian teu", "???_wrong1", "???_wrong2"],
        "hier": ["tian no", "???_wrong1", "???_wrong2"],
        "demain": ["namje", "???_wrong1", "???_wrong2"],
        "joie": ["ndo", "???_wrong1", "???_wrong2"],
        "tristesse": ["ngiene", "???_wrong1", "???_wrong2"],
        "colere": ["fuk", "???_wrong1", "???_wrong2"],
        "ami": ["mi lo", "???_wrong1", "???_wrong2"],
        "ennemi": ["mi tcheu", "???_wrong1", "???_wrong2"],
        "voisin": ["mi tsi", "???_wrong1", "???_wrong2"],
        "grand": ["loko", "???_wrong1", "???_wrong2"],
        "petit": ["tcho", "???_wrong1", "???_wrong2"],
        "beau": ["ndo lo", "???_wrong1", "???_wrong2"],
        "arachide": ["mbako", "???_wrong1", "???_wrong2"],
        "patate": ["mbape", "???_wrong1", "???_wrong2"],
        "tomate": ["tomate", "???_wrong1", "???_wrong2"],
        "doigt": ["naka tcho", "???_wrong1", "???_wrong2"],
        "genou": ["lote", "???_wrong1", "???_wrong2"],
        "epaule": ["biaka", "???_wrong1", "???_wrong2"],
        "croire": ["lo mbi", "???_wrong1", "???_wrong2"],
        "comprendre": ["tcheu lo", "???_wrong1", "???_wrong2"],
        "apprendre": ["tcheu lo", "???_wrong1", "???_wrong2"],
    },
}

bassa = {
    "debutant": {
        "bonjour": ["mieega", "???_wrong1", "???_wrong2"],
        "bonsoir": ["mieega njo", "???_wrong1", "???_wrong2"],
        "au revoir": ["yeghe", "???_wrong1", "???_wrong2"],
        "pere": ["bissou", "???_wrong1", "???_wrong2"],
        "mere": ["mam", "???_wrong1", "???_wrong2"],
        "frere": ["mbang", "???_wrong1", "???_wrong2"],
        "tete": ["lihi", "???_wrong1", "???_wrong2"],
        "oeil": ["lisho", "???_wrong1", "???_wrong2"],
        "oreille": ["tchok", "???_wrong1", "???_wrong2"],
        "eau": ["ngie", "???_wrong1", "???_wrong2"],
        "riz": ["mayi", "???_wrong1", "???_wrong2"],
        "igname": ["yam", "???_wrong1", "???_wrong2"],
        "un": ["oke", "???_wrong1", "???_wrong2"],
        "deux": ["meffe", "???_wrong1", "???_wrong2"],
        "trois": ["lator", "???_wrong1", "???_wrong2"],
        "blanc": ["pene", "???_wrong1", "???_wrong2"],
        "noir": ["tchue", "???_wrong1", "???_wrong2"],
        "rouge": ["peli", "???_wrong1", "???_wrong2"],
        "je": ["nde", "???_wrong1", "???_wrong2"],
        "tu": ["o", "???_wrong1", "???_wrong2"],
        "il": ["e", "???_wrong1", "???_wrong2"],
        "etre": ["bi", "???_wrong1", "???_wrong2"],
        "avoir": ["fa", "???_wrong1", "???_wrong2"],
        "faire": ["lo", "???_wrong1", "???_wrong2"],
    },
    "moyen": {
        "chien": ["tien", "???_wrong1", "???_wrong2"],
        "chat": ["mbeko", "???_wrong1", "???_wrong2"],
        "oiseau": ["nem", "???_wrong1", "???_wrong2"],
        "chemise": ["chemise", "???_wrong1", "???_wrong2"],
        "pantalon": ["pantalon", "???_wrong1", "???_wrong2"],
        "robe": ["robe", "???_wrong1", "???_wrong2"],
        "maison": ["ndang", "???_wrong1", "???_wrong2"],
        "porte": ["lihi ndang", "???_wrong1", "???_wrong2"],
        "fenetre": ["lisho ndang", "???_wrong1", "???_wrong2"],
        "soleil": ["yo", "???_wrong1", "???_wrong2"],
        "lune": ["ngie", "???_wrong1", "???_wrong2"],
        "etoile": ["nshie", "???_wrong1", "???_wrong2"],
        "route": ["tsin", "???_wrong1", "???_wrong2"],
        "marche": ["djang", "???_wrong1", "???_wrong2"],
        "ecole": ["ekol", "???_wrong1", "???_wrong2"],
        "voiture": ["kamio", "???_wrong1", "???_wrong2"],
        "moto": ["moto", "???_wrong1", "???_wrong2"],
        "velo": ["velo", "???_wrong1", "???_wrong2"],
        "fermier": ["tsang", "???_wrong1", "???_wrong2"],
        "enseignant": ["teuchua", "???_wrong1", "???_wrong2"],
        "medecin": ["ngang", "???_wrong1", "???_wrong2"],
        "marcher": ["dang", "???_wrong1", "???_wrong2"],
        "courir": ["ken", "???_wrong1", "???_wrong2"],
        "parler": ["lo", "???_wrong1", "???_wrong2"],
    },
    "fort": {
        "j'ai faim": ["nde coo", "???_wrong1", "???_wrong2"],
        "j'ai soif": ["nde nwe", "???_wrong1", "???_wrong2"],
        "j'ai froid": ["nde tue", "???_wrong1", "???_wrong2"],
        "aujourd'hui": ["nwa teu", "???_wrong1", "???_wrong2"],
        "hier": ["nwa no", "???_wrong1", "???_wrong2"],
        "demain": ["njo", "???_wrong1", "???_wrong2"],
        "joie": ["ndo", "???_wrong1", "???_wrong2"],
        "tristesse": ["ngiene", "???_wrong1", "???_wrong2"],
        "colere": ["fuk", "???_wrong1", "???_wrong2"],
        "ami": ["mi lo", "???_wrong1", "???_wrong2"],
        "ennemi": ["mi tcheu", "???_wrong1", "???_wrong2"],
        "voisin": ["mi tsi", "???_wrong1", "???_wrong2"],
        "grand": ["loko", "???_wrong1", "???_wrong2"],
        "petit": ["tcho", "???_wrong1", "???_wrong2"],
        "beau": ["ndo lo", "???_wrong1", "???_wrong2"],
        "arachide": ["mbako", "???_wrong1", "???_wrong2"],
        "patate": ["mbape", "???_wrong1", "???_wrong2"],
        "tomate": ["tomate", "???_wrong1", "???_wrong2"],
        "doigt": ["mikak tcho", "???_wrong1", "???_wrong2"],
        "genou": ["lote", "???_wrong1", "???_wrong2"],
        "epaule": ["biaka", "???_wrong1", "???_wrong2"],
        "croire": ["lo mbi", "???_wrong1", "???_wrong2"],
        "comprendre": ["tcheu lo", "???_wrong1", "???_wrong2"],
        "apprendre": ["tcheu lo", "???_wrong1", "???_wrong2"],
    },
}

bafan = {
    "debutant": {
        "bonjour": ["ma gho", "???_wrong1", "???_wrong2"],
        "bonsoir": ["ma gho nji", "???_wrong1", "???_wrong2"],
        "au revoir": ["o baa", "???_wrong1", "???_wrong2"],
        "pere": ["pa", "???_wrong1", "???_wrong2"],
        "mere": ["ma", "???_wrong1", "???_wrong2"],
        "frere": ["ngane", "???_wrong1", "???_wrong2"],
        "tete": ["loko", "???_wrong1", "???_wrong2"],
        "oeil": ["isho", "???_wrong1", "???_wrong2"],
        "oreille": ["tchoke", "???_wrong1", "???_wrong2"],
        "eau": ["ngie", "???_wrong1", "???_wrong2"],
        "riz": ["mayi", "???_wrong1", "???_wrong2"],
        "igname": ["yam", "???_wrong1", "???_wrong2"],
        "un": ["oke", "???_wrong1", "???_wrong2"],
        "deux": ["meffe", "???_wrong1", "???_wrong2"],
        "trois": ["lator", "???_wrong1", "???_wrong2"],
        "blanc": ["pene", "???_wrong1", "???_wrong2"],
        "noir": ["tchue", "???_wrong1", "???_wrong2"],
        "rouge": ["peli", "???_wrong1", "???_wrong2"],
        "je": ["nde", "???_wrong1", "???_wrong2"],
        "tu": ["o", "???_wrong1", "???_wrong2"],
        "il": ["e", "???_wrong1", "???_wrong2"],
        "etre": ["bi", "???_wrong1", "???_wrong2"],
        "avoir": ["fa", "???_wrong1", "???_wrong2"],
        "faire": ["lo", "???_wrong1", "???_wrong2"],
    },
    "moyen": {
        "chien": ["tien", "???_wrong1", "???_wrong2"],
        "chat": ["mbeko", "???_wrong1", "???_wrong2"],
        "oiseau": ["nem", "???_wrong1", "???_wrong2"],
        "chemise": ["chemise", "???_wrong1", "???_wrong2"],
        "pantalon": ["pantalon", "???_wrong1", "???_wrong2"],
        "robe": ["robe", "???_wrong1", "???_wrong2"],
        "maison": ["ndang", "???_wrong1", "???_wrong2"],
        "porte": ["loko ndang", "???_wrong1", "???_wrong2"],
        "fenetre": ["isho ndang", "???_wrong1", "???_wrong2"],
        "soleil": ["yo", "???_wrong1", "???_wrong2"],
        "lune": ["ngie", "???_wrong1", "???_wrong2"],
        "etoile": ["nshie", "???_wrong1", "???_wrong2"],
        "route": ["tsin", "???_wrong1", "???_wrong2"],
        "marche": ["djang", "???_wrong1", "???_wrong2"],
        "ecole": ["ekol", "???_wrong1", "???_wrong2"],
        "voiture": ["kamio", "???_wrong1", "???_wrong2"],
        "moto": ["moto", "???_wrong1", "???_wrong2"],
        "velo": ["velo", "???_wrong1", "???_wrong2"],
        "fermier": ["tsang", "???_wrong1", "???_wrong2"],
        "enseignant": ["teuchua", "???_wrong1", "???_wrong2"],
        "medecin": ["ngang", "???_wrong1", "???_wrong2"],
        "marcher": ["dang", "???_wrong1", "???_wrong2"],
        "courir": ["ken", "???_wrong1", "???_wrong2"],
        "parler": ["lo", "???_wrong1", "???_wrong2"],
    },
    "fort": {
        "j'ai faim": ["nde coo", "???_wrong1", "???_wrong2"],
        "j'ai soif": ["nde nwe", "???_wrong1", "???_wrong2"],
        "j'ai froid": ["nde tue", "???_wrong1", "???_wrong2"],
        "aujourd'hui": ["tian teu", "???_wrong1", "???_wrong2"],
        "hier": ["tian no", "???_wrong1", "???_wrong2"],
        "demain": ["namje", "???_wrong1", "???_wrong2"],
        "joie": ["ndo", "???_wrong1", "???_wrong2"],
        "tristesse": ["ngiene", "???_wrong1", "???_wrong2"],
        "colere": ["fuk", "???_wrong1", "???_wrong2"],
        "ami": ["mi lo", "???_wrong1", "???_wrong2"],
        "ennemi": ["mi tcheu", "???_wrong1", "???_wrong2"],
        "voisin": ["mi tsi", "???_wrong1", "???_wrong2"],
        "grand": ["loko", "???_wrong1", "???_wrong2"],
        "petit": ["tcho", "???_wrong1", "???_wrong2"],
        "beau": ["ndo lo", "???_wrong1", "???_wrong2"],
        "arachide": ["mbako", "???_wrong1", "???_wrong2"],
        "patate": ["mbape", "???_wrong1", "???_wrong2"],
        "tomate": ["tomate", "???_wrong1", "???_wrong2"],
        "doigt": ["naka tcho", "???_wrong1", "???_wrong2"],
        "genou": ["lote", "???_wrong1", "???_wrong2"],
        "epaule": ["biaka", "???_wrong1", "???_wrong2"],
        "croire": ["lo mbi", "???_wrong1", "???_wrong2"],
        "comprendre": ["tcheu lo", "???_wrong1", "???_wrong2"],
        "apprendre": ["tcheu lo", "???_wrong1", "???_wrong2"],
    },
}

bandjoun = {
    "debutant": {
        "bonjour": ["ma gho", "???_wrong1", "???_wrong2"],
        "bonsoir": ["ma gho nji", "???_wrong1", "???_wrong2"],
        "au revoir": ["o baa", "???_wrong1", "???_wrong2"],
        "pere": ["pa", "???_wrong1", "???_wrong2"],
        "mere": ["ma", "???_wrong1", "???_wrong2"],
        "frere": ["nenghane", "???_wrong1", "???_wrong2"],
        "tete": ["loko", "???_wrong1", "???_wrong2"],
        "oeil": ["isho", "???_wrong1", "???_wrong2"],
        "oreille": ["tchoke", "???_wrong1", "???_wrong2"],
        "eau": ["ngie", "???_wrong1", "???_wrong2"],
        "riz": ["mayi", "???_wrong1", "???_wrong2"],
        "igname": ["yam", "???_wrong1", "???_wrong2"],
        "un": ["oke", "???_wrong1", "???_wrong2"],
        "deux": ["meffe", "???_wrong1", "???_wrong2"],
        "trois": ["lator", "???_wrong1", "???_wrong2"],
        "blanc": ["pene", "???_wrong1", "???_wrong2"],
        "noir": ["tchue", "???_wrong1", "???_wrong2"],
        "rouge": ["peli", "???_wrong1", "???_wrong2"],
        "je": ["nde", "???_wrong1", "???_wrong2"],
        "tu": ["o", "???_wrong1", "???_wrong2"],
        "il": ["e", "???_wrong1", "???_wrong2"],
        "etre": ["bi", "???_wrong1", "???_wrong2"],
        "avoir": ["fa", "???_wrong1", "???_wrong2"],
        "faire": ["lo", "???_wrong1", "???_wrong2"],
    },
    "moyen": {
        "chien": ["tien", "???_wrong1", "???_wrong2"],
        "chat": ["mbeko", "???_wrong1", "???_wrong2"],
        "oiseau": ["nem", "???_wrong1", "???_wrong2"],
        "chemise": ["chemise", "???_wrong1", "???_wrong2"],
        "pantalon": ["pantalon", "???_wrong1", "???_wrong2"],
        "robe": ["robe", "???_wrong1", "???_wrong2"],
        "maison": ["ndang", "???_wrong1", "???_wrong2"],
        "porte": ["loko ndang", "???_wrong1", "???_wrong2"],
        "fenetre": ["isho ndang", "???_wrong1", "???_wrong2"],
        "soleil": ["yo", "???_wrong1", "???_wrong2"],
        "lune": ["ngie", "???_wrong1", "???_wrong2"],
        "etoile": ["nshie", "???_wrong1", "???_wrong2"],
        "route": ["tsin", "???_wrong1", "???_wrong2"],
        "marche": ["djang", "???_wrong1", "???_wrong2"],
        "ecole": ["ekol", "???_wrong1", "???_wrong2"],
        "voiture": ["kamio", "???_wrong1", "???_wrong2"],
        "moto": ["moto", "???_wrong1", "???_wrong2"],
        "velo": ["velo", "???_wrong1", "???_wrong2"],
        "fermier": ["tsang", "???_wrong1", "???_wrong2"],
        "enseignant": ["teuchua", "???_wrong1", "???_wrong2"],
        "medecin": ["ngang", "???_wrong1", "???_wrong2"],
        "marcher": ["dang", "???_wrong1", "???_wrong2"],
        "courir": ["ken", "???_wrong1", "???_wrong2"],
        "parler": ["lo", "???_wrong1", "???_wrong2"],
    },
    "fort": {
        "j'ai faim": ["nde coo", "???_wrong1", "???_wrong2"],
        "j'ai soif": ["nde nwe", "???_wrong1", "???_wrong2"],
        "j'ai froid": ["nde tue", "???_wrong1", "???_wrong2"],
        "aujourd'hui": ["tian teu", "???_wrong1", "???_wrong2"],
        "hier": ["tian no", "???_wrong1", "???_wrong2"],
        "demain": ["namje", "???_wrong1", "???_wrong2"],
        "joie": ["ndo", "???_wrong1", "???_wrong2"],
        "tristesse": ["ngiene", "???_wrong1", "???_wrong2"],
        "colere": ["fuk", "???_wrong1", "???_wrong2"],
        "ami": ["mi lo", "???_wrong1", "???_wrong2"],
        "ennemi": ["mi tcheu", "???_wrong1", "???_wrong2"],
        "voisin": ["mi tsi", "???_wrong1", "???_wrong2"],
        "grand": ["loko", "???_wrong1", "???_wrong2"],
        "petit": ["tcho", "???_wrong1", "???_wrong2"],
        "beau": ["ndo lo", "???_wrong1", "???_wrong2"],
        "arachide": ["mbako", "???_wrong1", "???_wrong2"],
        "patate": ["mbape", "???_wrong1", "???_wrong2"],
        "tomate": ["tomate", "???_wrong1", "???_wrong2"],
        "doigt": ["naka tcho", "???_wrong1", "???_wrong2"],
        "genou": ["lote", "???_wrong1", "???_wrong2"],
        "epaule": ["biaka", "???_wrong1", "???_wrong2"],
        "croire": ["lo mbi", "???_wrong1", "???_wrong2"],
        "comprendre": ["tcheu lo", "???_wrong1", "???_wrong2"],
        "apprendre": ["tcheu lo", "???_wrong1", "???_wrong2"],
    },
}

langues = {"bangante": bangante, "bassa": bassa, "bafan": bafan, "bandjoun": bandjoun}
